# .streamlit/secrets.toml
# Configuration des secrets pour micPlan - Persistance de session

[session]
# Configuration de la session - CORE pour éviter les déconnexions
enable_session_state_persistence = true
session_state_ttl_hours = 24
enable_auto_refresh = true
refresh_interval_seconds = 300

[streamlit]
# Configuration spécifique Streamlit pour la persistance
enable_session_state_persistence = true
session_state_ttl = 86400  # 24 heures en secondes
persist_session_state = true

[server]
# Configuration serveur pour la persistance
enableSessionStatePersistence = true
sessionStatePersistence = true

[client]
# Configuration client pour la persistance
sessionStatePersistence = true
enableSessionStatePersistence = true
